#!/bin/bash
echo "Checking DELETE /v2/images/{image_id}/tags/{tag}"
curl -i -X DELETE 'http://172.16.17.8:9292/v2/images/c37cd623-2d81-44e3-a811-5aafe81dce28/tags/OpenSUSE' -H "X-Auth-Token: $token" -H "Content: application/json" -H "Accept: application/json"
