#!/bin/bash
echo "Checking GET /v2/schemas/member"
curl -i -X GET http://172.16.17.8:9292/v2/schemas/member -H "X-Auth-Token: $token" -H "Content-Type: application/json" -H "Accept: application/json"
