#!/bin/bash
echo "Checking PUT /v2/images/{image_id}/members/{member_id}"
curl -i -X PUT http://172.16.17.8:9292/v2/images/c37cd623-2d81-44e3-a811-5aafe81dce28/members/29a17f9454314242a454ef2e5701abb3 -H "X-Auth-Token: $token" -d '{"status" : "accepted"}'

