#!/bin/bash
echo "Checking POST /v2/images/{image_id}/members"
curl -i -X POST http://172.16.17.8:9292/v2/images/c37cd623-2d81-44e3-a811-5aafe81dce28/members -H "X-Auth-Token: $token" -H "Content-Type: application/json" -H "Accept: application/json" -d '{"member": "29a17f9454314242a454ef2e5701abb3"}'
